config/routes.rb
Rails.application.routes.draw do
  resources :owls
  resources :hedgehogs
  resources :chicks
  resources :dogs
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: redirect("/cats")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_to(path, emoji, text)
    classes = %w[my-1 nav-link text-white]
    classes << "active" if current_page?(path)
    link_to(path, class: classes) do
      tag.span(class: "me-2") { emoji } + tag.span { text }
    end
  end

  def icon(icon_name)
    tag.i(class: [ "bi", "bi-#{icon_name}" ])
  end

  def icon_with_text(icon_name, text)
    tag.span(icon(icon_name), class: "me-2") + tag.span(text)
  end

  def turbo_stream_flash
    turbo_stream.append "flashes", partial: "flash"
  end
end

app/views/application/_flash.html.erb
<%# 成功時のToast %>
<% if notice %>
  <div class="mb-2 toast hide border-primary" data-controller="toast">
    <div class="toast-header text-primary">
      <strong class="me-auto"><%= icon_with_text("check-circle", "成功") %></strong>
      <button class="btn-close" data-bs-dismiss="toast">
    </div>
    <div class="toast-body"><%= notice %></div>
  </div>
<% end %>

<%# エラー時のToast %>
<% if alert %>
  <div class="mb-2 toast hide border-danger" data-controller="toast">
    <div class="toast-header text-danger">
      <strong class="me-auto"><%= icon_with_text("exclamation-circle", "エラー") %></strong>
      <button class="btn-close" data-bs-dismiss="toast">
    </div>
    <div class="toast-body"><%= alert %></div>
  </div>
<% end %>

app/views/application/_modal.html.erb
<%# `"modal"`という<turbo-frame>で囲う %>
<%= turbo_frame_tag "modal" do %>
  <%# modalコントローラーをアタッチする %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= title%></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/application/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 py-3 px-3 bg-dark text-white vh-100">
  <div class="d-flex align-items-center justify-content-center py-2">
    <%= link_to "AMS", root_path, class: "text-white display-6 text-decoration-none" %>
  </div>
  <hr />
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= sidebar_link_to(cats_path, "🐱", "ねこ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(dogs_path, "🐶", "いぬ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(chicks_path, "🐣", "ひよこ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(hedgehogs_path, "🦔", "ハリネズミ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(owls_path, "🦉", "フクロウ") %>
    </li>
  </ul>
</div>